services:
  db:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carrinho
    ports:
      - "5432:5432"
