services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carrinho
    ports:
      - "5432:5432"
  backend:
    build: .
    environment:
      DB_HOST: db
    depends_on:
      - db

volumes:
  pg_data:
